export const memesData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "angry.jpg",
        alt: "The Office moody",
    },
    {
        emotionTags: ["moody", "insomniac"],
        isGif: false,
        image: "angry2.png",
        alt: "The Office moody",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "angry3.jpg",
        alt: "The Office moody",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "confused.jpg",
        alt: "The Office confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: false,
        image: "dominant.jpg",
        alt: "The Office dominant",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "happy1.jpg",
        alt: "The Office happy",
    },
    {
        emotionTags: ["bored"],
        isGif: false,
        image: "bored.jpg",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: false,
        image: "bored2.png",
        alt: "The Office bored",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "insomnia.png",
        alt: "The Office insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "insomnia1.png",
        alt: "The Office insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "lazy.jpg",
        alt: "The Office lazy",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "lazy1.jpg",
        alt: "The Office lazy",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "nervous.jpg",
        alt: "The Office nervous",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "sad.png",
        alt: "The Office sad",
    },
    {
        emotionTags: ["sad", "moody"],
        isGif: false,
        image: "sad1.png",
        alt: "The Office sad",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "angry.gif",
        alt: "The Office moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "angry2.gif",
        alt: "The Office angry",
    }, 
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused2.gif",
        alt: "The Office confused",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused.gif",
        alt: "The Office confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "dominant.gif",
        alt: "The Office dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "happy.gif",
        alt: "The Office happy",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "happy1.gif",
        alt: "The Office happy",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "happy2.gif",
        alt: "The Office happy",
    },
    {
        emotionTags: ["bored", "sad", "confused"],
        isGif: true,
        image: "confused.gif",
        alt: "The Office hungry",
    },
    {
        emotionTags: ["bored", "confused"],
        isGif: true,
        image: "confused2.gif",
        alt: "The Office hungry",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored1.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored2.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored3.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored4.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored5.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["bored"],
        isGif: true,
        image: "bored6.gif",
        alt: "The Office bored",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomnia2.gif",
        alt: "The Office insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomnia1.gif",
        alt: "The Office insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomnia3.gif",
        alt: "The Office insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "relaxed.gif",
        alt: "The Office relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "relaxed1.gif",
        alt: "The Office relaxed",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "nervous.gif",
        alt: "The Office nervous",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "nervous1.gif",
        alt: "The Office nervous",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "nervous2.gif",
        alt: "The Office scared"
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad.gif",
        alt: "The Office sad",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad1.gif",
        alt: "The Office sad",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad2.gif",
        alt: "The Office sad",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad3.gif",
        alt: "The Office sad",
    },
]
